# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 paths:
   include:
     - src/auth-service/*
#resources:
#- repo: self
pool:
  vmImage: ubuntu-latest

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '938584ea-ffeb-4246-9c46-9fd5997474a8'
  imageRepository: 'authserviceapp'
  containerRegistry: 'eapenacrcicd.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/src/auth-service/Dockerfile'
  tag: '$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'src/auth-service/Dockerfile'
        tags: '$(tag)'

- stage: Push
  displayName: push stage
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'

#- stage: update
#  displayName: update
#  jobs:
#  - job: Update
#    displayName: Update
#    steps:
#    - task: ShellScript@2
#      inputs:
#        scriptPath: 'scripts/update_k8s.sh'
#        args: 'vote $(imageRepository) $(tag)'

